# 1. Port (stavio sam 8082 da izbjegnemo konflikt)
quarkus.http.port=8082

# 2. Baza - PROVJERI IME U pgAdmin-u! 
# Ako se u pgAdminu zove "autoservis" (malim slovima), stavi malim slovima ovdje.
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=1234
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/autoservis

# 3. Hibernate - ISPRAVLJENI KLJUČEVI
quarkus.hibernate-orm.log.sql=true
# Ispravan ključ za generisanje tabela:
quarkus.hibernate-orm.database.generation=drop-and-create
# Da vidimo tačno šta Hibernate radi
quarkus.log.category."org.hibernate.tool.schema".level=TRACE