quarkus.http.port=8082

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=1234
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/autoservis

quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.log.category."org.hibernate.tool.schema".level=TRACE

quarkus.oidc.auth-server-url=http://localhost:8180/realms/AutoServis
quarkus.oidc.client-id=quarkus-app
quarkus.oidc.application-type=service


# Opciono, ako želiš da kontrolišeš URL-ove odavde
quarkus.rest-client.ipify-api.url=https://api.ipify.org
quarkus.rest-client.time-api.url=https://timeapi.io/api/time/current
quarkus.oidc.tls.verification=none
